from dataclasses import dataclass
from pathlib import Path

@dataclass(frozen=True)
class Brick:
    name: str
    width: int
    depth: int
    height: int
    ldraw_part: str

BRICK_2X2 = Brick("2x2 brick", 2, 2, 1, "3003.dat")

@dataclass(frozen=True)
class Placement:
    brick: Brick
    x: int
    y: int
    z: int

class LegoGrid:
    def __init__(self, width, height, depth):
        self.width = width
        self.height = height
        self.depth = depth
        self.grid = [
            [[None for _ in range(depth)] for _ in range(height)]
            for _ in range(width)
        ]
        self.placements = []

    def can_place(self, brick, x, y, z):
        if x < 0 or y < 0 or z < 0:
            return False
        if x + brick.width > self.width:
            return False
        if y + brick.height > self.height:
            return False
        if z + brick.depth > self.depth:
            return False

        for dx in range(brick.width):
            for dy in range(brick.height):
                for dz in range(brick.depth):
                    if self.grid[x + dx][y + dy][z + dz] is not None:
                        return False
        return True

    def has_support(self, brick, x, y, z):
        if y == 0:
            return True

        for dx in range(brick.width):
            for dz in range(brick.depth):
                if self.grid[x + dx][y - 1][z + dz] is None:
                    return False
        return True

    def place(self, brick, x, y, z):
        if not self.can_place(brick, x, y, z):
            raise ValueError("Collision or out of bounds.")
        if not self.has_support(brick, x, y, z):
            raise ValueError("Brick is not supported.")

        placement = Placement(brick, x, y, z)

        for dx in range(brick.width):
            for dy in range(brick.height):
                for dz in range(brick.depth):
                    self.grid[x + dx][y + dy][z + dz] = placement

        self.placements.append(placement)
        return placement

    def print_layers(self):
        for y in range(self.height):
            print(f"\nLayer Y={y}")
            print("+" + "-" * self.width + "+")
            for z in range(self.depth):
                row = "".join(
                    "#" if self.grid[x][y][z] else "."
                    for x in range(self.width)
                )
                print("|" + row + "|")
            print("+" + "-" * self.width + "+")

def build_cube(width, height, depth):
    if width % 2 != 0 or depth % 2 != 0:
        raise ValueError("Width and depth must be even for this first version.")

    model = LegoGrid(width, height, depth)

    for y in range(height):
        for z in range(0, depth, BRICK_2X2.depth):
            for x in range(0, width, BRICK_2X2.width):
                model.place(BRICK_2X2, x, y, z)

    return model

def export_ldraw(model, filename, color=4):
    lines = [
        "0 LEGO Cube generated by Python",
        f"0 Size: {model.width} x {model.height} x {model.depth}",
        "0 !LDRAW_ORG Model",
    ]

    for p in model.placements:
        x = p.x * 20
        y = p.y * 24
        z = p.z * 20

        lines.append(
            f"1 {color} {x} {y} {z} "
            f"1 0 0 0 1 0 0 0 1 {p.brick.ldraw_part}"
        )

    lines.append("0 NOFILE")

    Path(filename).write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8"
    )

def main():
    width = height = depth = 6

    print(f"Building a {width} x {height} x {depth} LEGO cube...")

    model = build_cube(width, height, depth)

    print(f"Placed {len(model.placements)} bricks.")

    model.print_layers()

    # Save the LDraw file next to this Python script.
    output = Path(__file__).parent / "lego_cube_6x6x6.ldr"

    export_ldraw(model, output)

    print(f"\nCreated: {output}")


if __name__ == "__main__":
    main()
